# Generated by Django 5.2.6 on 2025-10-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
